[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"

[[tls.certificates]]
certFile = "/etc/traefik/certs/localhost/localhost.crt"
keyFile = "/etc/traefik/certs/localhost/localhost.key"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/etc/traefik/certs/localhost/localhost.crt"
      keyFile = "/etc/traefik/certs/localhost/localhost.key"

[tls.options]
  [tls.options.default]
    sniStrict = false
