defaultEntryPoints = ["http"]
logLevel = "INFO"
insecureSkipVerify = true

[traefikLog]
  format   = "json"

[accessLog]
  format = "json"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
swarmMode = true
network = "traefik"
exposedByDefault = true

[api]
entryPoint = "traefik"
dashboard = true
debug = false

  [api.statistics]
  recentErrors = 10

[ping]
  entryPoint = "traefik"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/wildcard.<domain>.com.br.crt"
      keyFile =  "/etc/traefik/certs/wildcard.<domain>.com.br.key"

[file]
  directory = "/etc/traefik/rules"
  watch = false
