[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    defaultRule = "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
    exposedByDefault = true
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"

[api]
  insecure = true
  dashboard = true
  debug = true

[accessLog]
  format = "json"

[log]
  level = "debug"

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"
  
  [entryPoints.metrics]
    address = ":8082"

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"
